package UIOLD;
import PreProcessing.WriteXmlFile;
import Pojo.AggregateFunc;
import Pojo.StarSchema;

import javax.xml.bind.JAXBException;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rachnajain
 */
public class AggregateFunctions extends javax.swing.JFrame {

    StarSchema globalSchema;
    HashSet<AggregateFunc> fns = new HashSet<AggregateFunc>();
    public AggregateFunctions(StarSchema s) {
        globalSchema = s;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkSum = new javax.swing.JCheckBox();
        chkCount = new javax.swing.JCheckBox();
        chkAverage = new javax.swing.JCheckBox();
        chkMean = new javax.swing.JCheckBox();
        chkMedian = new javax.swing.JCheckBox();
        chkMode = new javax.swing.JCheckBox();
        buttonProceed = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AggregateFunctions");

        jLabel1.setText("Choose Aggregate Function : ");

        chkSum.setText("Sum");

        chkCount.setText("Count");

        chkAverage.setText("Average");

        chkMean.setText("Mean");

        chkMedian.setText("Median");

        chkMode.setText("Mode");

        buttonProceed.setText("Proceed");
        buttonProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    buttonProceedActionPerformed(evt);
                }catch(Exception e)    {
                        System.out.println("error!!");
                    }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkMode)
                            .addComponent(chkMedian)
                            .addComponent(chkMean)
                            .addComponent(chkAverage)
                            .addComponent(chkCount)
                            .addComponent(chkSum)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(buttonProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(chkSum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkAverage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkMean)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkMedian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkMode)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonProceed)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void buttonProceedActionPerformed(java.awt.event.ActionEvent evt) throws JAXBException, FileNotFoundException {
        // TODO add your handling code here:
        if (chkSum.isSelected()){
            fns.add(AggregateFunc.SUM);
        }
        if (chkCount.isSelected()){
            fns.add(AggregateFunc.COUNT);
        }
        if (chkAverage.isSelected()){
            fns.add(AggregateFunc.AVG);
        }
        if (chkMean.isSelected()){
            fns.add(AggregateFunc.MEAN);
        }
        if (chkMedian.isSelected()){
            fns.add(AggregateFunc.MEDIAN);
        }
        if (chkMode.isSelected()){
            fns.add(AggregateFunc.MODE);
        }

        ArrayList<AggregateFunc> fnList = new ArrayList<AggregateFunc>(fns);
        globalSchema.setFunc(fnList);
        WriteXmlFile w = new WriteXmlFile(globalSchema);
        boolean  ans = w.writeSchema();
        if(ans)
            System.out.println("Schema Creation successful");
        else
            System.out.println("Unknown error occured while schema creation");
    }                                             


    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonProceed;
    private javax.swing.JCheckBox chkAverage;
    private javax.swing.JCheckBox chkCount;
    private javax.swing.JCheckBox chkMean;
    private javax.swing.JCheckBox chkMedian;
    private javax.swing.JCheckBox chkMode;
    private javax.swing.JCheckBox chkSum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration                   
}
